---
title: 'divergence'
header-includes:
   - \usepackage{tabularx, longtable, graphicx, csquotes, hyperref, color}
output:
  pdf_document:
    toc: true
    number_sections: true
---

```{r opts, echo = FALSE}
knitr::opts_chunk$set(
  dev = "png",
  fig.path = "fig/"
)
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.process = function(x) {
  x2 = sub('-\\d+([.][a-z]+)$', '\\1', x)
  if (file.rename(x, x2)) x2 else x
})
```


```{r, echo=FALSE, message=FALSE, warning=FALSE}

library(knitr)
library(ggplot2)
library(ggrepel)
library(gridExtra)
library(grid)
library(RColorBrewer)
library(GSEABase)
library(gplots)
library(reshape2)

library(bumphunter)

ggplot.theme = theme(axis.text.x = element_text(colour="grey20",size=20,angle=0,hjust=.5,vjust=.5,face="plain"),
               axis.text.y = element_text(colour="grey20",size=20,angle=0,hjust=1,vjust=0,face="plain"),  
               axis.title.x = element_text(colour="grey20",size=20,angle=0,hjust=.5,vjust=0,face="plain"),
               axis.title.y = element_text(colour="grey20",size=20,angle=90,hjust=.5,vjust=.5,face="plain"),
               plot.title = element_text(colour="grey20",size=20,angle=0,hjust=.5,vjust=0,face="plain"),
               legend.text = element_text(colour="grey20",size=20,angle=0,hjust=.5,vjust=0,face="plain"),
               legend.title = element_text(colour="grey20",size=20,angle=0,hjust=.5,vjust=0,face="plain"),
               legend.key.height=unit(1.5, "line"),
               panel.grid.major = element_line(colour="darkgray"))

```

\section{Finding divergent cpg clusters}

```{r, echo=FALSE}

# load processed data

l1 = load("data_1.rda")
l2 = load("data_2.rda")

```


```{r, echo=FALSE, message=FALSE, warning=FALSE}

# assemble cpg data

cpgs.all = unique(data.cpg.ann$id)

cpg.ann.list = lapply(cpgs.all, function(x){
  y = which(data.cpg.ann$id == x)
  list(
  cpg = x,
  chr = data.cpg.ann$seqnames[ y[1] ],
  start = data.cpg.ann$start[ y[1] ],
  annot.strand = unique(data.cpg.ann$annot.strand[y]),
  annot.width = unique(data.cpg.ann$annot.width[y]),
  annot.symbol = unique(data.cpg.ann$annot.symbol[y]),
  annot.type = unique(data.cpg.ann$annot.type[y]),
  annot.dist = unique(data.cpg.ann$DistanceFromAnn[y])
  )
})
names(cpg.ann.list) = cpgs.all

# select cpgs available in TCGA data

cpg.ann.list = cpg.ann.list[names(cpg.ann.list)[which(names(cpg.ann.list) %in% rownames(div.met$Mat.div))]]

# make clusters
cpg.chr = sapply(cpg.ann.list, function(x) x$chr)
cpg.pos = sapply(cpg.ann.list, function(x) x$start)

cpg.clusts = clusterMaker(chr=cpg.chr, pos=cpg.pos, assumeSorted=FALSE, maxGap=300)

cpg.clusts.list = lapply(unique(cpg.clusts), function(i) names(cpg.ann.list)[which(cpg.clusts == i)] )
names(cpg.clusts.list) = unique(cpg.clusts)

# use binary divergence

mat.temp = abs(div.met$Mat.div)

# run permutations
m = 1000
mat.rand = sapply(1:m, function(j) sample(1:nrow(mat.temp)))

div.sum.rand = apply(mat.rand, 2, function(z){
  
   mat.temp.rand = mat.temp
   rownames(mat.temp.rand) = rownames(mat.temp)[z]

   sapply(cpg.clusts.list, function(x) sum(mat.temp.rand[x, ]))

})

# get cluster divergence sums
div.clust.sum = sapply(cpg.clusts.list, function(x) sum(mat.temp[x, ]))

# prepare data for bumphunter

sel.samples = intersect(colnames(mat.met), rownames(data.pheno))

mat.met = mat.met[names(cpg.ann.list), sel.samples]
pheno.met = data.pheno[sel.samples, ]

sel.normal = which(pheno.met$sample_type == "Solid Tissue Normal")
sel.tumor = which(pheno.met$sample_type == "Primary Tumor")

df.bump = data.frame(sample=colnames(mat.met)[c(sel.normal, sel.tumor)],
                     group=c(rep("NORMAL", length(sel.normal)), rep("TUMOR", length(sel.tumor)) ) )
mod.bump = model.matrix(~group, df.bump)

m = 500
mat.rand = sapply(1:m, function(j) sample(1:nrow(mat.met)))

save(mat.met, df.bump, mod.bump, cpg.chr, cpg.pos, cpg.clusts, mat.rand, file="data_bump_1.rda")

bumps = bumphunter(mat.met[, df.bump$sample],
                   design=mod.bump, chr=cpg.chr, pos=cpg.pos, cluster=cpg.clusts, maxGap=300,
                  pickCutoff=TRUE, nullMethod="permutation", permutations=mat.rand)

# assemble dmr results from bumphunter

bumps.clusts.list = lapply(unique(bumps$table$cluster), function(j){
  bumps$table[which(bumps$table$cluster == j), ]
})
names(bumps.clusts.list) = unique(bumps$table$cluster)

bumps.table = data.frame(clust=names(bumps.clusts.list),
                         p=sapply(bumps.clusts.list, function(x) min(x$p.value)),
                         area=sapply(bumps.clusts.list, function(x) max(x$area)),
                         value=sapply(bumps.clusts.list, function(x) x$value[which.max(abs(x$value))])
)

# standardize cluster divergence sums

div.clust.sum.norm = div.clust.sum/sapply(cpg.clusts.list, length)

# compute p-values

div.sum.rand.p = sapply(1:length(div.clust.sum), function(j){
  sum(div.sum.rand[j, ] >= div.clust.sum[j])/ncol(div.sum.rand)
})

sum.table = data.frame(clust=names(div.clust.sum),
                       value=div.clust.sum,
                       value2=div.clust.sum/ncol(mat.temp),
                       value.norm=div.clust.sum.norm,
                       p=div.sum.rand.p)

# compare results

bumps.table = bumps.table[order(bumps.table$p), ]
sum.table = sum.table[order(sum.table$p), ]

sel.clusts = intersect(rownames(bumps.table), rownames(sum.table))

df.bp = bumps.table[sel.clusts, ]
df.sum = sum.table[sel.clusts, ]

sum.table$pbon = p.adjust(sum.table$p, method="bon")

sum.table.sig = sum.table[which(sum.table$pbon <= 0.05), ]

sum.table.sig = sum.table.sig[order(sum.table.sig$value, decreasing=TRUE), ]

sel.cl = sum.table.sig$clust[1:100]

top.df = data.frame(t(sapply(sel.cl, function(x){

  y = cpg.clusts.list[[x]]

  w = cpg.ann.list[y]
  
  c(chr=w[[1]]$chr,
    start=min(sapply(w, function(z) z$start)),
    end=max(sapply(w, function(z) z$start+3)),
    cpgs=length(y),
    genes=paste(unique(Reduce(c, lapply(w, function(z) z$annot.symbol))), collapse=",")
  )
  
})))

```


```{r fig_clust_area, echo=FALSE, message=FALSE, warning=FALSE, fig.width=6, fig.height=6, results='asis'}

ggplot(data.frame(x=df.bp$area, y=df.sum$value2), aes(x=x, y=y))+
  geom_point(size=2)+
  xlab("cluster area (bumphunter)")+
  ylab("cluster divergence")+
  ggplot.theme

```


```{r fig_clust_value, echo=FALSE, message=FALSE, warning=FALSE, fig.width=7, fig.height=6, results='asis'}

ggplot(data.frame(x=df.bp$value, y=df.sum$value.norm), aes(x=x, y=y))+
  geom_point(size=2)+
  xlab("cluster max value (bumphunter)")+
  ylab("cluster normalized divergence sum")+
  ggplot.theme

```















