---
title: 'divergence'
header-includes:
   - \usepackage{tabularx, longtable, graphicx, csquotes, hyperref, color}
output:
  pdf_document:
    toc: true
    number_sections: true
---

```{r opts, echo = FALSE}
knitr::opts_chunk$set(
  dev = "png",
  fig.path = "fig/"
)
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.process = function(x) {
  x2 = sub('-\\d+([.][a-z]+)$', '\\1', x)
  if (file.rename(x, x2)) x2 else x
})
```


```{r, echo=FALSE, message=FALSE, warning=FALSE}

library(knitr)
library(ggplot2)
library(ggrepel)
library(gridExtra)
library(grid)
library(RColorBrewer)
library(GSEABase)
library(gplots)
library(reshape2)

ggplot.theme = theme(axis.text.x = element_text(colour="grey20",size=20,angle=0,hjust=.5,vjust=.5,face="plain"),
               axis.text.y = element_text(colour="grey20",size=20,angle=0,hjust=1,vjust=0,face="plain"),  
               axis.title.x = element_text(colour="grey20",size=20,angle=0,hjust=.5,vjust=0,face="plain"),
               axis.title.y = element_text(colour="grey20",size=20,angle=90,hjust=.5,vjust=.5,face="plain"),
               plot.title = element_text(colour="grey20",size=20,angle=0,hjust=.5,vjust=0,face="plain"),
               legend.text = element_text(colour="grey20",size=20,angle=0,hjust=.5,vjust=0,face="plain"),
               legend.title = element_text(colour="grey20",size=20,angle=0,hjust=.5,vjust=0,face="plain"),
               legend.key.height=unit(1.5, "line"),
               panel.grid.major = element_line(colour="darkgray"))

```

\section{Finding gene-cpg pairs}


```{r, echo=FALSE}

# load data

l1 = load("data_1.rda")
l2 = load("data_2.rda")
l3 = load("data_3.rda")

```


```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.width=10, fig.height=6}

# prepare cpg - gene data

cpg.genes.mat = intersect(cpg.genes.all, rownames(mat.exp))

cpg.ann.mat.list = lapply(cpg.ann.list, function(x) intersect(x$annot.symbol, cpg.genes.mat) )
cpg.ann.mat.list = cpg.ann.mat.list[which(sapply(cpg.ann.mat.list, length) > 0)]

cpg.ann.mat.list = cpg.ann.mat.list[which(names(cpg.ann.mat.list) %in% rownames(div.met$Mat.div))]

samples.met.exp = intersect(colnames(div.met$Mat.div), colnames(div.exp$Mat.div))

# compute cpg - gene co-divertent proportions

cpg.gene.cross.list = lapply(1:length(cpg.ann.mat.list), function(j){

  x = names(cpg.ann.mat.list)[j]
  y = cpg.ann.mat.list[[j]]

  as.vector( abs(div.met$Mat.div[x, samples.met.exp, drop=FALSE]) %*% abs(t(div.exp$Mat.div[y, samples.met.exp, drop=FALSE])) )

})

# make pair labels

u = lapply(1:length(cpg.ann.mat.list), function(j) paste(cpg.ann.mat.list[[j]], names(cpg.ann.mat.list)[j], sep=",") )

v = rep("", sum(sapply(u, length)))
w = rep(NA, length(v))

j = 1
for(i in 1:length(u)){
  m = length(u[[i]])
  v[j:(j+m-1)] = u[[i]]
  w[j:(j+m-1)] = cpg.gene.cross.list[[i]]/length(samples.met.exp)
  
  j = j+m
}

# assemble results

v.pair = t(sapply(v, function(x) unname(unlist( strsplit(x, ",") ) )))

df.pair = data.frame(pair=v, value=w, gene=v.pair[, 1], cpg=v.pair[, 2])

df.pair = df.pair[order(df.pair$value, decreasing=TRUE), ]

df.pair.sel = df.pair[1:10000, ]

# compute correlations

sel.samples = intersect(colnames(mat.met), colnames(mat.exp))

pheno.common = data.pheno[sel.samples, ]

sel.normal = rownames(pheno.common)[which(pheno.common$sample_type == "Solid Tissue Normal")]
sel.tumor = rownames(pheno.common)[which(pheno.common$sample_type == "Primary Tumor")]

cor.all = cor(t(mat.met[df.pair.sel$cpg, sel.samples]), t(mat.exp[df.pair.sel$gene, sel.samples]))
cor.normal = cor(t(mat.met[df.pair.sel$cpg, sel.normal]), t(mat.exp[df.pair.sel$gene, sel.normal]))
cor.tumor = cor(t(mat.met[df.pair.sel$cpg, sel.tumor]), t(mat.exp[df.pair.sel$gene, sel.tumor]))

df.pair.sel$cor.all = sapply(1:nrow(df.pair.sel), function(i) cor.all[df.pair.sel$cpg[i], df.pair.sel$gene[i]] )
df.pair.sel$cor.normal = sapply(1:nrow(df.pair.sel), function(i) cor.normal[df.pair.sel$cpg[i], df.pair.sel$gene[i]] )
df.pair.sel$cor.tumor = sapply(1:nrow(df.pair.sel), function(i) cor.tumor[df.pair.sel$cpg[i], df.pair.sel$gene[i]] )

pair.sel.dist = sapply(1:nrow(df.pair.sel), function(i){
  x = cpg.ann.list[[df.pair.sel$cpg[i]]]
  x$annot.dist[which.min(abs(x$annot.dist))]
})

```

```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.width=10, fig.height=6}

# compute concordant and discordant proportions

df.conc.disc = data.frame(t(sapply(1:20, function(i){

  cpg = df.pair.sel$cpg[i]
  g = df.pair.sel$gene[i]

  d_exp = div.exp$Mat.div[g, samples.met.exp]
  d_met = div.met$Mat.div[cpg, samples.met.exp]

  c(
    value=df.pair.sel$value[i],
    # abs(d_exp) %*% abs(d_met) / length(samples.met.exp)
    value2=sum(abs(d_exp) > 0 & abs(d_met) > 0) / length(samples.met.exp),

    conc=mean(sign(d_exp) == sign(d_met) & abs(d_exp) > 0 & abs(d_met) > 0),

    disc=mean(sign(d_exp) != sign(d_met) & abs(d_exp) > 0 & abs(d_met) > 0)
  )
  
})))

rownames(df.conc.disc) = rownames(df.pair.sel)[1:nrow(df.conc.disc)]

```


```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.width=10, fig.height=6}

df.pair.sel.top = df.pair.sel[1:15, ]

df.pair.sel.top$chr = sapply(df.pair.sel.top$cpg, function(x) cpg.ann.list[[x]]$chr )
df.pair.sel.top$start = sapply(df.pair.sel.top$cpg, function(x) cpg.ann.list[[x]]$start )

df.pair.sel.top$conc = round(df.conc.disc[rownames(df.pair.sel.top), "conc"], 3)
df.pair.sel.top$disc = round(df.conc.disc[rownames(df.pair.sel.top), "disc"], 3)

df.pair.sel.top = df.pair.sel.top[, c("cpg", "gene", "value", "conc", "disc", "chr", "start")]

df.pair.sel.top$value = round(df.pair.sel.top$value, 3)


```


```{r fig_pair_cor, echo=FALSE, message=FALSE, warning=FALSE, fig.width=8, fig.height=6, results='asis'}

df.plot = data.frame(x=df.pair.sel$cor.all, y=df.pair.sel$value, gene=df.pair.sel$gene, dist=pair.sel.dist)

ggplot(df.plot, aes(x=x, y=y))+
  geom_point(size=2)+
  geom_text_repel(data=df.plot[1:100, ], aes(x=x, y=y, label=gene))+
  xlab("methylation - expression correlation")+
  ylab("proportion of co-divergent samples")+
  ggplot.theme


```


```{r fig_pair_dist, echo=FALSE, message=FALSE, warning=FALSE, fig.width=8, fig.height=6, results='asis'}

ggplot(df.plot, aes(x=dist, y=y))+
  geom_point(size=2)+
  xlab("gene annotation distance")+
  ylab("proportion of co-divergent samples")+
  ggplot.theme

```










