---
title: 'divergence'
header-includes:
   - \usepackage{tabularx, longtable, graphicx, csquotes, hyperref, color}
output:
  pdf_document:
    toc: true
    number_sections: true
---

```{r opts, echo = FALSE}
knitr::opts_chunk$set(
  fig.path = "fig/"
)
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.process = function(x) {
  x2 = sub('-\\d+([.][a-z]+)$', '\\1', x)
  if (file.rename(x, x2)) x2 else x
})
```


```{r, echo=FALSE, message=FALSE, warning=FALSE}

library(knitr)
library(ggplot2)
library(ggrepel)
library(gridExtra)
library(grid)
library(RColorBrewer)
library(GSEABase)
library(gplots)
library(reshape2)

ggplot.theme = theme(axis.text.x = element_text(colour="grey20",size=20,angle=0,hjust=.5,vjust=.5,face="plain"),
               axis.text.y = element_text(colour="grey20",size=20,angle=0,hjust=1,vjust=0,face="plain"),  
               axis.title.x = element_text(colour="grey20",size=20,angle=0,hjust=.5,vjust=0,face="plain"),
               axis.title.y = element_text(colour="grey20",size=20,angle=90,hjust=.5,vjust=.5,face="plain"),
               plot.title = element_text(colour="grey20",size=20,angle=0,hjust=.5,vjust=0,face="plain"),
               legend.text = element_text(colour="grey20",size=20,angle=0,hjust=.5,vjust=0,face="plain"),
               legend.title = element_text(colour="grey20",size=20,angle=0,hjust=.5,vjust=0,face="plain"),
               legend.key.height=unit(1.5, "line"),
               panel.grid.major = element_line(colour="darkgray"))

```


\section{Multivariate divergence workflow}

```{r, echo=FALSE}

l1 = load("data_1.rda")

```

\subsection{Divergence values}

```{r fig8, echo=FALSE, message=FALSE, warning=FALSE, fig.width=18, fig.height=6}

mat.temp = div.exp.KEGG$Mat.div

t1=sample(1:nrow(mat.temp), 5)

df = melt(mat.temp[t1, ])
colnames(df) = c("pathway", "sample", "value")
df$value = factor(df$value)
df$pathway = gsub("KEGG_", "", df$pathway)

ggplot(df, aes(x=pathway, fill=value))+
  geom_bar()+xlab("KEGG gene set")+ylab("sample count")+
  ggplot.theme+coord_flip()+
  scale_fill_manual(name="divergence state", values=c("gray20", "violetred4"))+
  theme(legend.position="bottom")

rm(df)

```


```{r fig9, echo=FALSE, message=FALSE, warning=FALSE, fig.width=18, fig.height=6}

mat.temp = div.exp.KEGG$Mat.div

t1=sort(sample(1:ncol(mat.temp), 5))

df = melt(mat.temp[, t1])
colnames(df) = c("pathway", "sample", "value")
df$value = factor(df$value)
df$sample = factor(df$sample, levels=colnames(mat.temp[, t1]))

ggplot(df, aes(x=sample, fill=value))+
  geom_bar()+xlab("sample")+ylab("KEGG geneset count")+
  ggplot.theme+coord_flip()+
  scale_fill_manual(name="divergence state", values=c("gray20", "dodgerblue4"))+
  theme(legend.position="bottom")

rm(df)

```

\subsection{Diffentially divergent pathways}

```{r fig10, echo=FALSE, message=FALSE, warning=FALSE, fig.width=10, fig.height=10}

sel.ER = which(pheno.exp$ER_Status_nature2012 %in% c("Negative", "Positive"))
sel.ER.samples = rownames(pheno.exp)[sel.ER]
groups.ER = pheno.exp$ER_Status_nature2012[sel.ER]

chi.KEGG = divergence.preSE::computeChiSquaredTest(Mat=div.exp.KEGG$Mat.div[, sel.ER.samples], 
                                 Groups=groups.ER, 
                                 classes=c("Negative", "Positive"))

df = data.frame(
  gene=rownames(div.exp.KEGG$Mat.div),
  pPOS=rowMeans(abs(div.exp.KEGG$Mat.div[, sel.ER.samples[which(groups.ER == "Positive")]] )),
  pNEG=rowMeans(abs(div.exp.KEGG$Mat.div[, sel.ER.samples[which(groups.ER == "Negative")]] )),
  chi.KEGG[rownames(div.exp.KEGG$Mat.div), ]
)
df$padj = p.adjust(df$pval, method="bonferroni")
df$sig = factor(df$padj <= 0.05, levels=c(NA, "FALSE", "TRUE", "X"))
df$sig[order(df$padj)[1:10]] = "X"
df$gene2 = gsub("KEGG_", "", as.character(df$gene))
df$gene2[order(df$padj)[-c(1:10)]] = NA

df = df[order(df$sig), ]

ggplot(df, aes(x=pPOS, y=pNEG, col=sig))+
  geom_point()+
  geom_abline(slope=1)+
  scale_color_manual(name="", values=c("gray40", "steelblue3", "steelblue4"))+
  geom_text_repel(aes(x=pPOS, y=pNEG, label=gene2))+
  xlab("divergent probability, ER+")+
  ylab("divergent probability, ER-")+
  ggplot.theme+theme(legend.position="none")

rm(df)

```

\subsection{PCA analysis}

```{r fig11, echo=FALSE, message=FALSE, warning=FALSE, fig.width=6, fig.height=6}

levels.pam50 = c("Luminal A", "Luminal B", "HER2-enriched", "Basal-like")

sel.PAM50 = which(pheno.exp$PAM50_mRNA_nature2012 %in% levels.pam50)
sel.PAM50.samples = rownames(pheno.exp)[sel.PAM50]
groups.PAM50 = factor(pheno.exp$PAM50_mRNA_nature2012[sel.PAM50], levels=levels.pam50)

pca = prcomp(t(div.exp.KEGG$Mat.div[, sel.PAM50.samples]))
pca.mat = pca$x
pca.eigen = pca$sdev^2
pca.v = pca.eigen/sum(pca.eigen)

df = data.frame(PAM=groups.PAM50, pca.mat[sel.PAM50.samples, 1:2])

ggplot(df, aes(x=PC1, y=PC2, col=PAM))+
    geom_point()+
    xlab(sprintf("PC1 [%.1f%% variance]", pca.v[1]*100))+
    ylab(sprintf("PC2 [%.1f%% variance]", pca.v[2]*100))+   
    ggplot.theme+theme(legend.position="bottom", legend.direction="vertical")+
    scale_color_manual(name="PAM50 subtype", values=brewer.pal(4, "Set2"))

rm(df)

```

















